[package]
name = "open-lark"
version = "0.5.0"
edition = "2021"
authors = ["ZoOL <zhooul@gmail.com>"]
readme = "README.md"
description = "Lark/Feishu Open API SDK(WIP)"
keywords = ["sdk", "feishu", "lark", "rest"]
categories = ["api-bindings"]
documentation = "https://docs.rs/open-lark"
repository = "https://github.com/foxzool/open-lark"
homepage = "https://github.com/foxzool/open-lark"
license = "MIT OR Apache-2.0"

[features]
websocket = ["tokio-tungstenite", "prost", "lark-websocket-protobuf"]

[workspace]
members = ["crates/*"]

[dependencies]
lark-websocket-protobuf = { path = "crates/protobuf", version = "0.1.1", optional = true }

anyhow = "1.0.86"
base64 = "0.22.1"
chrono = { version = "0.4.38", features = ["serde"] }
futures-util = { version = "0.3.30", default-features = false, features = [
    "sink",
    "std",
] }
hmac = "0.12.1"
log = "0.4.21"
prost = { version = "0.13", optional = true }
quick_cache = { version = "0.6.3", features = [] }
reqwest = { version = "0.12.7", default-features = false, features = [
    "json",
    "multipart",
    "rustls-tls",
] }
rand = "0.8"
simd-adler32 = "0.3.7"
serde_repr = "0.1.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
strum = "0.27"
strum_macros = "0.27"
thiserror = "2.0"
tokio = { version = "1.38", features = ["rt", "rt-multi-thread", "macros"] }
url = { version = "2.5.0", features = ["serde"] }
tokio-tungstenite = { version = "0.23", features = [
    "rustls-tls-native-roots",
], optional = true }


[dev-dependencies]
dotenvy = "0.15.7"
dotenv = "0.15.0"
env_logger = "0.11.3"
uuid = { version = "1.8.0", features = ["v4"] }
chrono = { version = "0.4.38", features = ["serde"] }

# ===========================================
# Examples
# ===========================================

[[example]]
name = "client_setup"
path = "examples/basic/client_setup.rs"

[[example]]
name = "send_message"
path = "examples/api/send_message.rs"

[[example]]
name = "websocket_client"
path = "examples/basic/websocket_client.rs"
required-features = ["websocket"]

[[example]]
name = "cloud_docs_test"
path = "examples/cloud_docs_test.rs"

[[example]]
name = "enhanced_builder_demo"
path = "examples/enhanced_builder_demo.rs"

[[example]]
name = "enhanced_drive_operations"
path = "examples/api/enhanced_drive_operations.rs"

[[example]]
name = "drive_builder_execute_demo"
path = "examples/api/drive_builder_execute_demo.rs"