[package]
name = "open-lark"
version = "0.5.0"
edition = "2021"
authors = ["ZoOL <zhooul@gmail.com>"]
readme = "README.md"
description = "Lark/Feishu Open API SDK(WIP)"
keywords = ["sdk", "feishu", "lark", "rest"]
categories = ["api-bindings"]
documentation = "https://docs.rs/open-lark"
repository = "https://github.com/foxzool/open-lark"
homepage = "https://github.com/foxzool/open-lark"
license = "MIT OR Apache-2.0"

[features]
websocket = ["tokio-tungstenite", "prost", "lark-websocket-protobuf"]

[workspace]
members = ["crates/*"]

[dependencies]
lark-websocket-protobuf = { path = "crates/protobuf", version = "0.1.1", optional = true }

anyhow = "1.0.86"
async-recursion = "1.1.1"
base64 = "0.22.1"
chrono = { version = "0.4.38", features = ["serde"] }
futures-util = { version = "0.3.30", default-features = false, features = [
    "sink",
    "std",
] }
hmac = "0.12.1"
lazy_static = "1.4.0"
log = "0.4.21"
prost = { version = "0.13", optional = true }
quick_cache = { version = "0.6.3", features = [] }
reqwest = { version = "0.12.7", default-features = false, features = [
    "json",
    "multipart",
    "rustls-tls",
] }
simd-adler32 = "0.3.7"
serde_repr = "0.1.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
strum = "0.27"
strum_macros = "0.27"
thiserror = "2.0"
tokio = { version = "1.38", features = ["rt", "rt-multi-thread", "macros"] }
url = { version = "2.5.0", features = ["serde"] }
tokio-tungstenite = { version = "0.23", features = [
    "rustls-tls-native-roots",
], optional = true }


[dev-dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.3"
uuid = { version = "1.8.0", features = ["v4"] }

[[example]]
name = "ws_client"
path = "examples/ws_client.rs"
required-features = ["websocket"]


[[example]]
name = "card_column_set"
path = "examples/card/column_set.rs"

[[example]]
name = "card_form_set"
path = "examples/card/form.rs"

[[example]]
name = "card_interactive"
path = "examples/card/interactive.rs"

[[example]]
name = "card_collapsible"
path = "examples/card/collapsible.rs"

[[example]]
name = "create_message"
path = "examples/api/im/v1/create_message.rs"

[[example]]
name = "list_message"
path = "examples/api/im/v1/list_message.rs"

[[example]]
name = "list_chat"
path = "examples/api/im/v1/list_chat.rs"

[[example]]
name = "file_upload_all"
path = "examples/api/drive/v1/files/upload_all.rs"

[[example]]
name = "file_download"
path = "examples/api/drive/v1/files/download.rs"


[[example]]
name = "root_meta"
path = "examples/api/drive/v2/explorer/meta.rs"

[[example]]
name = "create_folder"
path = "examples/api/drive/v2/explorer/create_folder.rs"

[[example]]
name = "list_folder"
path = "examples/api/drive/v2/explorer/list_folder.rs"

[[example]]
name = "get_permission"
path = "examples/api/drive/v2/permission/get.rs"

[[example]]
name = "patch_permission"
path = "examples/api/drive/v2/permission/patch.rs"

[[example]]
name = "search_user"
path = "examples/api/search/v1/user.rs"

# 电子表格

[[example]]
name = "sheet-add-rows-or-columns"
path = "examples/api/sheets/v2/spreadsheet/add_row_or_columns.rs"

[[example]]
name = "sheet-insert-rows-or-columns"
path = "examples/api/sheets/v2/spreadsheet/insert_row_or_columns.rs"

[[example]]
name = "sheet-update-rows-or-columns"
path = "examples/api/sheets/v2/spreadsheet/update_row_or_columns.rs"

# 删除行列
[[example]]
name = "sheet-delete-rows-or-columns"
path = "examples/api/sheets/v2/spreadsheet/delete_row_or_columns.rs"

# 插入数据
[[example]]
name = "sheet-prepend_data"
path = "examples/api/sheets/v2/data-operation/prepend_data.rs"

# 追加数据
[[example]]
name = "sheet-append_data"
path = "examples/api/sheets/v2/data-operation/append_data.rs"

# 读取单个范围
[[example]]
name = "sheet-reading_a_single_range"
path = "examples/api/sheets/v2/data-operation/reading_a_single_range.rs"

# 向单个范围写入数据
[[example]]
name = "sheet-write_a_single_range"
path = "examples/api/sheets/v2/data-operation/write_a_single_range.rs"

# 读取多个范围
[[example]]
name = "sheet-reading_multi_ranges"
path = "examples/api/sheets/v2/data-operation/reading_multi_ranges.rs"

# 向单个范围写入数据
[[example]]
name = "sheet-write_multi_ranges"
path = "examples/api/sheets/v2/data-operation/write_multi_ranges.rs"

# 设置单元格样式
[[example]]
name = "sheet-set_cell_style"
path = "examples/api/sheets/v2/data-operation/set_cell_style.rs"

# 批量设置单元格样式
[[example]]
name = "sheet-write_image"
path = "examples/api/sheets/v2/data-operation/write_image.rs"

# 写入图片
[[example]]
name = "sheet-batch_set_cell_style"
path = "examples/api/sheets/v2/data-operation/batch_set_cell_style.rs"

# 合并单元格
[[example]]
name = "sheet-merge_cells"
path = "examples/api/sheets/v2/data-operation/merge_cells.rs"

# 拆分单元格
[[example]]
name = "sheet-split_cells"
path = "examples/api/sheets/v2/data-operation/split_cells.rs"

# 操作工作表
[[example]]
name = "operate_spreadsheet_sheet"
path = "examples/api/sheets/v2/spreadsheet-sheet/operate.rs"

# 更新工作表属性
[[example]]
name = "update_spreadsheet_sheet_properties"
path = "examples/api/sheets/v2/spreadsheet-sheet/update.rs"

# 查找单元格
[[example]]
name = "sheet-find_cells"
path = "examples/api/sheets/v3/data_operation/find_cells.rs"

# 替换单元格
[[example]]
name = "sheet-relace_cells"
path = "examples/api/sheets/v3/data_operation/replace_cells.rs"

[[example]]
name = "create_spreadsheet"
path = "examples/api/sheets/v3/spreadsheet/create.rs"

[[example]]
name = "patch_spreadsheet"
path = "examples/api/sheets/v3/spreadsheet/patch.rs"

[[example]]
name = "get_spreadsheet"
path = "examples/api/sheets/v3/spreadsheet/get.rs"

# 查询工作表
[[example]]
name = "get_spreadsheet_sheet"
path = "examples/api/sheets/v3/spreadsheet-sheet/get.rs"

# 获取工作表
[[example]]
name = "query_spreadsheet_sheet"
path = "examples/api/sheets/v3/spreadsheet-sheet/query.rs"

# 移动行列
[[example]]
name = "sheet_move_dimension"
path = "examples/api/sheets/v3/spreadsheet-sheet/move_dimension.rs"

# 获取筛选
[[example]]
name = "spreadsheet-sheet-filter-get"
path = "examples/api/sheets/v3/spreadsheet-sheet-filter/get.rs"

# 创建筛选
[[example]]
name = "spreadsheet-sheet-filter-create"
path = "examples/api/sheets/v3/spreadsheet-sheet-filter/create.rs"

# 更新筛选
[[example]]
name = "spreadsheet-sheet-filter-update"
path = "examples/api/sheets/v3/spreadsheet-sheet-filter/update.rs"

# 删除筛选
[[example]]
name = "spreadsheet-sheet-filter-delete"
path = "examples/api/sheets/v3/spreadsheet-sheet-filter/delete.rs"

[[example]]
name = "get_bitable"
path = "examples/api/bitable/v1/app/get.rs"


[[example]]
name = "app_table_field_list"
path = "examples/api/bitable/v1/app_table_field/list.rs"


[[example]]
name = "auth_get_user_info"
path = "examples/api/authen/v1/user_info.rs"


[[example]]
name = "app_table_record_create"
path = "examples/api/bitable/v1/app_table_record/create.rs"

# 更新记录
[[example]]
name = "app_table_record_update"
path = "examples/api/bitable/v1/app_table_record/update.rs"

[[example]]
name = "app_table_record_batch_create"
path = "examples/api/bitable/v1/app_table_record/batch_create.rs"

[[example]]
name = "app_table_record_search"
path = "examples/api/bitable/v1/app_table_record/search.rs"

# 考勤班次管理 - 单独接口示例
[[example]]
name = "attendance_shift_create"
path = "examples/api/attendance/v1/shift/create.rs"

[[example]]
name = "attendance_shift_delete"
path = "examples/api/attendance/v1/shift/delete.rs"

[[example]]
name = "attendance_shift_get"
path = "examples/api/attendance/v1/shift/get.rs"

[[example]]
name = "attendance_shift_query"
path = "examples/api/attendance/v1/shift/query.rs"

[[example]]
name = "attendance_shift_list"
path = "examples/api/attendance/v1/shift/list.rs"

# 考勤排班管理
[[example]]
name = "attendance_user_daily_shift_batch_create"
path = "examples/api/attendance/v1/user_daily_shift/batch_create.rs"

[[example]]
name = "attendance_user_daily_shift_query"
path = "examples/api/attendance/v1/user_daily_shift/query.rs"

[[example]]
name = "attendance_user_daily_shift_batch_create_temp"
path = "examples/api/attendance/v1/user_daily_shift/batch_create_temp.rs"

# 考勤组管理
[[example]]
name = "attendance_group_list_user"
path = "examples/api/attendance/v1/group/list_user.rs"

[[example]]
name = "attendance_group_create"
path = "examples/api/attendance/v1/group/create.rs"

[[example]]
name = "attendance_group_delete"
path = "examples/api/attendance/v1/group/delete.rs"

[[example]]
name = "attendance_group_get"
path = "examples/api/attendance/v1/group/get.rs"

[[example]]
name = "attendance_group_search"
path = "examples/api/attendance/v1/group/search.rs"

[[example]]
name = "attendance_group_list"
path = "examples/api/attendance/v1/group/list.rs"

# 考勤用户设置
[[example]]
name = "attendance_user_setting_modify"
path = "examples/api/attendance/v1/user_setting/modify.rs"

[[example]]
name = "attendance_user_setting_query"
path = "examples/api/attendance/v1/user_setting/query.rs"

[[example]]
name = "attendance_user_setting_upload"
path = "examples/api/attendance/v1/user_setting/upload.rs"

[[example]]
name = "attendance_user_setting_download"
path = "examples/api/attendance/v1/user_setting/download.rs"

# 考勤统计
[[example]]
name = "attendance_user_stats_data_update"
path = "examples/api/attendance/v1/user_stats_data/update.rs"

[[example]]
name = "attendance_user_stats_data_query_settings"
path = "examples/api/attendance/v1/user_stats_data/query_settings.rs"

[[example]]
name = "attendance_user_stats_data_query_fields"
path = "examples/api/attendance/v1/user_stats_data/query_fields.rs"

[[example]]
name = "attendance_user_stats_data_query_data"
path = "examples/api/attendance/v1/user_stats_data/query_data.rs"

# 假勤审批
[[example]]
name = "attendance_user_approval_query"
path = "examples/api/attendance/v1/user_approval/query.rs"

[[example]]
name = "attendance_user_approval_create"
path = "examples/api/attendance/v1/user_approval/create.rs"

[[example]]
name = "attendance_user_approval_process"
path = "examples/api/attendance/v1/user_approval/process.rs"

# 考勤事件
[[example]]
name = "attendance_events"
path = "examples/event/attendance/attendance_events.rs"

# 考勤补卡
[[example]]
name = "attendance_user_task_remedy_create"
path = "examples/api/attendance/v1/user_task_remedy/create.rs"

[[example]]
name = "attendance_user_task_remedy_query_user_allowed_remedys"
path = "examples/api/attendance/v1/user_task_remedy/query_user_allowed_remedys.rs"

[[example]]
name = "attendance_user_task_remedy_query"
path = "examples/api/attendance/v1/user_task_remedy/query.rs"

# 归档报表管理
[[example]]
name = "attendance_archive_rule_query_user_stats_fields"
path = "examples/api/attendance/v1/archive_rule/query_user_stats_fields.rs"

[[example]]
name = "attendance_archive_rule_upload_report"
path = "examples/api/attendance/v1/archive_rule/upload_report.rs"

[[example]]
name = "attendance_archive_rule_del_report"
path = "examples/api/attendance/v1/archive_rule/del_report.rs"

[[example]]
name = "attendance_archive_rule_list"
path = "examples/api/attendance/v1/archive_rule/list.rs"

# 休假管理
[[example]]
name = "attendance_leave_employ_expire_record_get"
path = "examples/api/attendance/v1/leave_employ_expire_record/get.rs"

[[example]]
name = "attendance_leave_accrual_record_patch"
path = "examples/api/attendance/v1/leave_accrual_record/patch.rs"
