name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New API endpoint support
        - SDK functionality enhancement
        - Developer experience improvement
        - Documentation improvement
        - Performance optimization
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
    validations:
      required: false

  - type: textarea
    id: api_design
    attributes:
      label: API Design (if applicable)
      description: How would you like the API to look?
      render: rust
    validations:
      required: false

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to implement this feature
        - label: I'm willing to help with testing
        - label: I'm willing to help with documentation